@startuml

'# Diagrama de Clase - TransportationManager

'## CLASES

'Definicion de VEHICULOS
class Vehiculo {
    -matricula: String
    -modelo: String
    -marca: String
    -capacidad: double
}

enum Estado {
    DISPONIBLE
    EN_SERVICIO
    FUERA_SERVICIO
}

'Tipos de VEHICULOS
class Camioneta {

}

class Furgoneta {

}

class Motocicleta {

}

'Definicion de CONDUCTORES
class Conductor {
    -nombre: String
    -id: int
    -licencia: String
    -direccion: String
}

class Empleado {
    
}

class Contratista {

}

'Definicion de RUTAS
class Ruta {
    -codigo: int
    -descripcion: String
    -distancia: double
    -duracion: float
}

class RutaNacional {

}

class RutaInternacional {

}

'Definicion de ENVIOS
class Envio {

}

class EnvioRegular {

}

class EnvioUrgente {

}

'## RELACIONES

'Definicion de relacion *Composicion* Vehiculo-Estado
Vehiculo "0..*" *-- "1" Estado: -estado: Estado
'Definicion de relacion *Herencia* Vehiculo-Camioneta
Vehiculo <|-- Camioneta 
'Definicion de relacion *Herencia* Vehiculo-Furgoneta
Vehiculo <|-- Furgoneta 
'Definicion de relacion *Herencia* Vehiculo-Motocicleta
Vehiculo <|-- Motocicleta 

'Definicion de relacion *Agregacion* Vehiculo-Conductor
Vehiculo "0..*" o-- "1" Conductor: -conductor: Conductor

'Definicion de relacion *Herencia* Conductor-Empleado
Conductor <|-- Empleado
'Definicion de relacion *Herencia* Conductor-Contratista
Conductor <|-- Contratista

'Definicion de relacion *Herencia* Ruta-RutaNacional
Ruta <|-- RutaNacional
'Definicion de relacion *Herencia* Ruta-RutaInternacional
Ruta <|-- RutaInternacional 

'Definicion de relacion *Herencia* Ruta-RutaNacional
Envio <|-- EnvioRegular
'Definicion de relacion *Herencia* Ruta-RutaInternacional
Envio <|-- EnvioUrgente

@enduml